### ISSUE TITLE
"app__left-column" is horizontally compressed on mobile depending on width of browser window

### ISSUE THREAD

**Issue by gemabrow** [Open-Source-Medical-Supplies/osms-libraries#13]
![Screen Shot 2020-07-17 at 4 41 56 PM](https://user-images.githubusercontent.com/7517312/87838988-ba308380-c84d-11ea-8618-95edfd86a802.png)

**Comment by JoshMLeslie** [comment]
fixed in 2591b69bbf56f793eabe9030ec3ffc63414dc4aa
