### ISSUE TITLE
Project / Category param gets corrupted when FB (etc) attaches more to the query

### ISSUE THREAD

**Issue by JoshMLeslie** [Open-Source-Medical-Supplies/osms-libraries#2]
link eg:
`https://opensourcemedicalsupplies.org/libraries/project-library/?project=10-06-TIPPY&fbclid=IwAR3zy2PU17dEhhLdzfkYkHGtLnALF6BLMJ8RBzprX3WcVNCpoEFRjbrT0l8`

currently parses to `10-06-TIPPY&fbclid=IwAR3zy2PU17dEhhLdzfkYkHGtLnALF6BLMJ8RBzprX3WcVNCpoEFRjbrT0l8`

which doesn't work. `getParam()` needs to be stricter.

**Comment by JoshMLeslie** [comment]
I updated this some to use project names as opposed to their ID (mainly just because rocks were already falling that way)

The functions moved to `src/shared/utility/param-handling.ts`

**Comment by charchow** [comment]
I wonder if this is what made the search weird? I'm trying to figure out how to integrate this: https://stackoverflow.com/a/12151322

**Comment by JoshMLeslie** [comment]
closing in favor of #14
